apiVersion: v1
kind: Service
metadata:
  name: blue-service
spec:
  selector:
    app: blue # Initially routes to the Blue deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
